Lab4/Lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from cleaning.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls', namespace='administration')),
    path('cleaning/', include('cleaning.urls')),
    path('', RedirectView.as_view(url='cleaning/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Lab4/administration/urls.py
from django.urls import path

import administration.views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'administration'

urlpatterns = [
    path('', views.index, name='list_servicepack'),
    path('create/', administration.views.ServicePackCreate.as_view(), name='create_servicepack'),
    path('delete/<int:id>/', administration.views.ServicePackDelete.as_view(), name='delete_servicepack'),
    path('edit/<int:id>/', administration.views.ServicePackEdit.as_view(), name='edit_servicepack')
]

Lab4/administration/models.py
from django.db import models

# Create your models here.

Lab4/administration/forms.py
from django import forms

from cleaning.models import Service, ServicePack, ServicePackInstance


class ServicePackInstanceForm(forms.ModelForm):
    date_created = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = ServicePackInstance
        fields = ['status', 'price', 'date_created']

    def __init__(self, service_pack, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.service_pack = service_pack

    def save(self, commit=True):
        servicepackinstance = super().save(commit=False)
        servicepackinstance.service_pack = self.service_pack

        if commit:
            servicepackinstance.save()
        self.save_m2m()
        return servicepackinstance


class ServicePackForm(forms.ModelForm):
    class Meta:
        model = ServicePack
        fields = ('naming', 'service')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:  # Edit existing object
            self.fields['service'].initial = self.instance.service.all()

    def save(self, commit=True):
        servicepack = super().save(commit=False)
        if commit:
            servicepack.save()
        if self.cleaned_data['service']:
            servicepack.service.set(self.cleaned_data['service'])
        else:
            servicepack.service.clear()
        self.save_m2m()
        return servicepack

Lab4/administration/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin

from administration.forms import ServicePackForm
from cleaning.models import ServicePack


# Create your views here.
@user_passes_test(lambda user: user.groups.filter(name='Admin').exists())
def index(request):
    servicepacks = ServicePack.objects.all()
    return render(request, "administration/list_servicepack.html", {"servicepacks": servicepacks})


class ServicePackCreate(UserPassesTestMixin, View):
    def get(self, request):
        form = ServicePackForm()
        return render(request, 'administration/create_servicepack.html', {'form': form})

    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()

    def post(self, request):
        form = ServicePackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('administration:list_servicepack')
        return render(request, 'administration/create_servicepack.html', {'form': form})


class ServicePackEdit(View):
    def get(self, request, id):
        servicepack = get_object_or_404(ServicePack, id=id)
        form = ServicePackForm(instance=servicepack)
        return render(request, 'administration/edit_servicepack.html', {'servicepack': servicepack, 'form': form})

    def post(self, request, id):
        servicepack = get_object_or_404(ServicePack, id=id)
        form = ServicePackForm(request.POST, instance=servicepack)
        if form.is_valid():
            form.save()
            return redirect('administration:list_servicepack')
        return render(request, 'administration/edit_servicepack.html', {'servicepack': servicepack, 'form': form})


class ServicePackDelete(View):
    def get(self, request, id):
        servicepack = get_object_or_404(ServicePack, id=id)
        return render(request, 'administration/delete_servicepack.html', {'servicepack': servicepack})

    def post(self, request, id):
        servicepack = get_object_or_404(ServicePack, id=id)
        servicepack.delete()
        return redirect('administration:list_servicepack')

Lab4/administration/templates/administration/create_servicepack.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Create New Service Pack</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

Lab4/administration/templates/administration/delete_servicepack.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Lab4/administration/templates/administration/edit_servicepack.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Edit Service Pack</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

Lab4/administration/templates/administration/list_servicepack.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Service Pack List</h1>
    {% if servicepacks %}
        <ul>
            <form action="{% url 'administration:create_servicepack' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Create">
            </form>

            {% for servicepack in servicepacks %}
                <li>
                    <a href="{{ servicepack.get_absolute_url }}">{{ servicepack.naming }}</a>

                </li>
                <form action="{% url 'administration:edit_servicepack' servicepack.id %}" method="post">
                    {{ cart_servicepack_form }}
                    {% csrf_token %}
                    <input type="submit" value="Edit">
                </form>
                <form action="{% url 'administration:delete_servicepack' servicepack.id %}" method="post">
                    {{ cart_servicepack_form }}
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
            {% endfor %}

        </ul>
    {% else %}
        <p>There are no service packs.</p>
    {% endif %}
{% endblock %}