Lab4/Lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from cleaning.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls', namespace='administration')),
    path('cleaning/', include('cleaning.urls')),
    path('', RedirectView.as_view(url='cleaning/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Lab4/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<uuid:servicepackinstance_id>/', views.cart_add, name='cart_add'),
    path('remove/<uuid:servicepackinstance_id>/', views.cart_remove, name='cart_remove'),
]

Lab4/cleaning/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('servicepacks/', views.ServicePackListView.as_view(), name='servicepacks'),
    path('servicepack/<int:pk>', views.ServicePackDetailView.as_view(), name='servicepack-detail')
]

Lab4/cleaning/models.py
from django.db import models
from django.urls import reverse
import uuid


# Create your models here.

class Service(models.Model):
    """Model for Service itself."""
    name = models.CharField(max_length=100, help_text="Enter the service to perform")

    def __str__(self):
        return self.name


class ServicePack(models.Model):
    """Model for Service Pack."""
    naming = models.CharField(max_length=200, help_text="Enter the service pack naming")
    service = models.ManyToManyField(Service, help_text='Select a service for this service pack')
    purchase_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.naming

    def get_absolute_url(self):
        return reverse('servicepack-detail', args=[str(self.id)])

    def display_service(self):
        return ', '.join(service.name for service in self.service.all()[:3])

    display_service.short_description = 'Service'


class ServicePackInstance(models.Model):
    """Specific Service pack which can or cannot be purchased."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for particular Service Pack")
    service_pack = models.ForeignKey('ServicePack', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default='0.00')
    date_created = models.DateField(null=True, blank=True)
    purchase_count = models.PositiveIntegerField(default=0)

    AVAILABLE_STATUS = (
        ('a', 'Available'),
        ('o', 'Out of stock'),
        ('c', 'Coming soon')
    )

    status = models.CharField(
        max_length=1,
        choices=AVAILABLE_STATUS,
        blank=True,
        default='a',
        help_text='Service pack availability'
    )

    class Meta:
        ordering = ['price']

    def __str__(self):
        return f'{self.id} '

Lab4/cleaning/forms.py
import re
from datetime import date

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ExtendedUserCreationForm(UserCreationForm):
    USER_ROLE_CHOICES = [
        ('customer', 'Customer'),
        ('staff', 'Staff'),
        ('admin', 'Admin'),
    ]

    user_role = forms.ChoiceField(
        choices=USER_ROLE_CHOICES,
        widget=forms.RadioSelect,
        required=True
    )

    def clean(self):
        cleaned_data = super().clean()
        user_role = cleaned_data.get('user_role')
        if not user_role:
            raise forms.ValidationError('Please select a user role.')
        return cleaned_data

    email = forms.EmailField(label='Email')
    date_of_birth = forms.DateField(label='Birth date', widget=forms.DateInput(attrs={'type': 'date'}))
    phone = forms.CharField(max_length=20, label='Phone')
    first_name = forms.CharField(max_length=100, label='First Name')
    second_name = forms.CharField(max_length=100, label='Second Name')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'date_of_birth', 'phone', 'first_name', 'second_name', 'user_role')

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        if date_of_birth:
            today = date.today()
            age = today.year - date_of_birth.year - (
                        (today.month, today.day) < (date_of_birth.month, date_of_birth.day))
            if age < 18:
                raise forms.ValidationError("You must be at least 18 years old to register.")
        return date_of_birth

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            if not re.match(r'^\+375\d{9}$', phone):
                raise forms.ValidationError("Phone number must be in the format +375XXXXXXXXX.")
        return phone

Lab4/cleaning/views.py
import requests
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ExtendedUserCreationForm
from .models import ServicePack, ServicePackInstance, Service
from django.views import generic

# Define the user roles
UNAUTHORIZED_ROLE = 'Unauthorized'
CUSTOMER_ROLE = 'Customer'
STAFF_ROLE = 'Staff'
ADMIN_ROLE = 'Admin'

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Assign the appropriate role based on the form data
            user_role = form.cleaned_data['user_role']
            if user_role == 'staff':
                group = Group.objects.get_or_create(name='Staff')[0]
                user.groups.add(group)
            elif user_role == 'admin':
                group = Group.objects.get_or_create(name='Admin')[0]
                user.groups.add(group)
            else:
                group = Group.objects.get_or_create(name='Customer')[0]
                user.groups.add(group)
            user.save()
            login(request, user)
            return redirect('index')
    else:
        form = ExtendedUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def index(request):
    """View function for home page of site."""
    if request.method == 'POST':
        name = request.POST.get('name')
        if name:
            response = requests.get(f'https://api.agify.io/?name={name}')
            if response.status_code == 200:
                data = response.json()
                age = data.get('age')
            else:
                age = "Failed to retrieve age."
        else:
            age = None
    else:
        name = None
        age = None

    num_service_packs = ServicePack.objects.all().count()
    num_instances = ServicePackInstance.objects.all().count()
    num_instances_available = ServicePackInstance.objects.filter(status__exact='a').count()

    try:
        response = requests.get('https://api.kanye.rest/')

        if response.status_code == 200:
            data = response.json()
            quote = data["quote"]
        else:
            quote = "Failed to retrieve quote."
    except:
        quote = ""

    context = {
        'num_service_packs': num_service_packs,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'quote': quote,
        'age': age,
        'name': name,
    }

    return render(request, 'index.html', context=context)


class ServicePackListView(generic.ListView):
    model = ServicePack
    template_name = 'cleaning/servicepack_list.html'



class ServicePackDetailView(generic.DetailView):
    model = ServicePack
    template_name = 'cleaning/servicepack_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        servicepack = self.get_object()
        price_filter = self.request.GET.get('price')

        if price_filter:
            filtered_copies = servicepack.servicepackinstance_set.filter(price__lt=price_filter)
        else:
            filtered_copies = servicepack.servicepackinstance_set.all()

        context['filtered_copies'] = filtered_copies
        context['price_filter'] = price_filter
        return context

Lab4/cleaning/templates/cleaning/servicepack_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Naming: {{ servicepack.naming }}</h1>

    <p><strong>Provided services:</strong> {{ servicepack.service.all|join:", " }}</p>

    <form method="GET">
        <label for="price-filter">Filter by price:</label>
        <label>
            <input type="number" name="price" value="{{ price_filter }}" placeholder="Enter price filter"
                   pattern="[0-9]+">
        </label>
        <button type="submit">Apply</button>
    </form>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Available Packs</h4>

        {% for copy in filtered_copies %}
            <hr/>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'o' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Not available now</strong></p>
            {% endif %}
            <p><strong>Price:</strong> ${{ copy.price }}</p>
            <p><strong>Date can be booked on:</strong> {{ copy.date_created }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>

            {% if user.is_authenticated and copy.status == 'a' %}
                {% for group in user.groups.all %}
                    {% if group.name == 'Customer' %}
                        <form action="{% url 'cart:cart_add' copy.id %}" method="post">
                            {{ cart_servicepack_form }}
                            {% csrf_token %}
                            <input type="submit" value="Add to cart">
                        </form>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

Lab4/cleaning/templates/cleaning/servicepack_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Service Pack List</h1>

    <div class="servicepack-row">
        {% if servicepack_list %}
            {% for servicepack in servicepack_list %}
                <div class="servicepack-item">
                    <a href="{{ servicepack.get_absolute_url }}">{{ servicepack.naming }}</a>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no service packs.</p>
        {% endif %}
    </div>

    <style>
        .servicepack-row {
            display: flex;
            flex-wrap: wrap;
        }

        .servicepack-item {
            margin-right: 10px;
        }
    </style>
{% endblock %}