Lab4/Lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from cleaning.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls', namespace='administration')),
    path('cleaning/', include('cleaning.urls')),
    path('', RedirectView.as_view(url='cleaning/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Lab4/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<uuid:servicepackinstance_id>/', views.cart_add, name='cart_add'),
    path('remove/<uuid:servicepackinstance_id>/', views.cart_remove, name='cart_remove'),
]

Lab4/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order-detail'),

]

Lab4/cart/models.py
from django.db import models

# Create your models here.

Lab4/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from cleaning.models import ServicePack, ServicePackInstance
from .cart import Cart
from django.core.exceptions import PermissionDenied

@require_POST
def cart_add(request, servicepackinstance_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("No access")

    cart = Cart(request)
    servicepackinstance = get_object_or_404(ServicePackInstance, id=servicepackinstance_id)

    # Check if the service pack instance is available
    if servicepackinstance.status != 'a':
        return redirect('cart:cart_detail')

    cart.add(servicepackinstance=servicepackinstance, quantity=1)
    servicepackinstance.status = 'o'
    servicepackinstance.save()
    return redirect('cart:cart_detail')

def cart_remove(request, servicepackinstance_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("No access")

    cart = Cart(request)
    servicepackinstance = get_object_or_404(ServicePackInstance, id=servicepackinstance_id)
    cart.remove(servicepackinstance)
    servicepackinstance.status = 'a'
    servicepackinstance.save()
    return redirect('cart:cart_detail')

def cart_detail(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("No access")
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

Lab4/cart/templates/cart/detail.html
{% extends "base_generic.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <style>
        .cart td, .cart th {
            margin: 20px;
        }

        .cart {
            width: 40%;
            text-align: center;
        }

        .cart th {
            text-align: center;
        }

        .cart td {
            text-align: center;
            vertical-align: middle;
        }

        .cart .total {
            margin-top: 20px;
            border-top: 2px solid black;
            font-weight: bold;
            text-align: right;
            position: relative;
        }
    </style>

    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Service Pack</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with servicepackinstance=item.servicepackinstance %}
                <tr>
                    <td><a>{{ servicepackinstance.service_pack.naming }}</a></td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' servicepackinstance.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total ">
            <td>Total</td>
            <td colspan="3"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <div class="checkout" style="margin-top: 10px; text-align: left;">
        <a href="{% url 'order:order_create' %}" class="button">
            Checkout
        </a>
    </div>
{% endblock %}