Lab4/Lab4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

from cleaning.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls', namespace='administration')),
    path('cleaning/', include('cleaning.urls')),
    path('', RedirectView.as_view(url='cleaning/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Lab4/administration/urls.py
from django.urls import path

import administration.views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'administration'

urlpatterns = [
    path('', views.index, name='list_servicepack'),
    path('create/', administration.views.ServicePackCreate.as_view(), name='create_servicepack'),
    path('delete/<int:id>/', administration.views.ServicePackDelete.as_view(), name='delete_servicepack'),
    path('edit/<int:id>/', administration.views.ServicePackEdit.as_view(), name='edit_servicepack')
]

Lab4/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<uuid:servicepackinstance_id>/', views.cart_add, name='cart_add'),
    path('remove/<uuid:servicepackinstance_id>/', views.cart_remove, name='cart_remove'),
]

Lab4/cleaning/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('servicepacks/', views.ServicePackListView.as_view(), name='servicepacks'),
    path('servicepack/<int:pk>', views.ServicePackDetailView.as_view(), name='servicepack-detail')
]

Lab4/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order-detail'),

]

Lab4/cleaning/models.py
from django.db import models
from django.urls import reverse
import uuid


# Create your models here.

class Service(models.Model):
    """Model for Service itself."""
    name = models.CharField(max_length=100, help_text="Enter the service to perform")

    def __str__(self):
        return self.name


class ServicePack(models.Model):
    """Model for Service Pack."""
    naming = models.CharField(max_length=200, help_text="Enter the service pack naming")
    service = models.ManyToManyField(Service, help_text='Select a service for this service pack')
    purchase_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.naming

    def get_absolute_url(self):
        return reverse('servicepack-detail', args=[str(self.id)])

    def display_service(self):
        return ', '.join(service.name for service in self.service.all()[:3])

    display_service.short_description = 'Service'


class ServicePackInstance(models.Model):
    """Specific Service pack which can or cannot be purchased."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for particular Service Pack")
    service_pack = models.ForeignKey('ServicePack', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default='0.00')
    date_created = models.DateField(null=True, blank=True)
    purchase_count = models.PositiveIntegerField(default=0)

    AVAILABLE_STATUS = (
        ('a', 'Available'),
        ('o', 'Out of stock'),
        ('c', 'Coming soon')
    )

    status = models.CharField(
        max_length=1,
        choices=AVAILABLE_STATUS,
        blank=True,
        default='a',
        help_text='Service pack availability'
    )

    class Meta:
        ordering = ['price']

    def __str__(self):
        return f'{self.id} '

Lab4/cleaning/forms.py
import re
from datetime import date

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ExtendedUserCreationForm(UserCreationForm):
    USER_ROLE_CHOICES = [
        ('customer', 'Customer'),
        ('staff', 'Staff'),
        ('admin', 'Admin'),
    ]

    user_role = forms.ChoiceField(
        choices=USER_ROLE_CHOICES,
        widget=forms.RadioSelect,
        required=True
    )

    def clean(self):
        cleaned_data = super().clean()
        user_role = cleaned_data.get('user_role')
        if not user_role:
            raise forms.ValidationError('Please select a user role.')
        return cleaned_data

    email = forms.EmailField(label='Email')
    date_of_birth = forms.DateField(label='Birth date', widget=forms.DateInput(attrs={'type': 'date'}))
    phone = forms.CharField(max_length=20, label='Phone')
    first_name = forms.CharField(max_length=100, label='First Name')
    second_name = forms.CharField(max_length=100, label='Second Name')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'date_of_birth', 'phone', 'first_name', 'second_name', 'user_role')

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        if date_of_birth:
            today = date.today()
            age = today.year - date_of_birth.year - (
                        (today.month, today.day) < (date_of_birth.month, date_of_birth.day))
            if age < 18:
                raise forms.ValidationError("You must be at least 18 years old to register.")
        return date_of_birth

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if phone:
            if not re.match(r'^\+375\d{9}$', phone):
                raise forms.ValidationError("Phone number must be in the format +375XXXXXXXXX.")
        return phone

Lab4/cleaning/views.py
import requests
from django.contrib.auth import login
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ExtendedUserCreationForm
from .models import ServicePack, ServicePackInstance, Service
from django.views import generic

# Define the user roles
UNAUTHORIZED_ROLE = 'Unauthorized'
CUSTOMER_ROLE = 'Customer'
STAFF_ROLE = 'Staff'
ADMIN_ROLE = 'Admin'

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = ExtendedUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Assign the appropriate role based on the form data
            user_role = form.cleaned_data['user_role']
            if user_role == 'staff':
                group = Group.objects.get_or_create(name='Staff')[0]
                user.groups.add(group)
            elif user_role == 'admin':
                group = Group.objects.get_or_create(name='Admin')[0]
                user.groups.add(group)
            else:
                group = Group.objects.get_or_create(name='Customer')[0]
                user.groups.add(group)
            user.save()
            login(request, user)
            return redirect('index')
    else:
        form = ExtendedUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def index(request):
    """View function for home page of site."""
    if request.method == 'POST':
        name = request.POST.get('name')
        if name:
            response = requests.get(f'https://api.agify.io/?name={name}')
            if response.status_code == 200:
                data = response.json()
                age = data.get('age')
            else:
                age = "Failed to retrieve age."
        else:
            age = None
    else:
        name = None
        age = None

    num_service_packs = ServicePack.objects.all().count()
    num_instances = ServicePackInstance.objects.all().count()
    num_instances_available = ServicePackInstance.objects.filter(status__exact='a').count()

    try:
        response = requests.get('https://api.kanye.rest/')

        if response.status_code == 200:
            data = response.json()
            quote = data["quote"]
        else:
            quote = "Failed to retrieve quote."
    except:
        quote = ""

    context = {
        'num_service_packs': num_service_packs,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'quote': quote,
        'age': age,
        'name': name,
    }

    return render(request, 'index.html', context=context)


class ServicePackListView(generic.ListView):
    model = ServicePack
    template_name = 'cleaning/servicepack_list.html'



class ServicePackDetailView(generic.DetailView):
    model = ServicePack
    template_name = 'cleaning/servicepack_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        servicepack = self.get_object()
        price_filter = self.request.GET.get('price')

        if price_filter:
            filtered_copies = servicepack.servicepackinstance_set.filter(price__lt=price_filter)
        else:
            filtered_copies = servicepack.servicepackinstance_set.all()

        context['filtered_copies'] = filtered_copies
        context['price_filter'] = price_filter
        return context

Lab4/cleaning/templates/base_generic.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
<html lang="en">
<head>
    {% block title %}
        <title>Cleaning company</title>
    {% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <style>
        .sidebar-nav {
            display: flex;
            flex-wrap: wrap;
            justify-content: flex-start;
            list-style: none;
            padding: 0;
        }

        .sidebar-nav li {
            margin-right: 10px;
        }

        .sidebar-nav a {
            text-decoration: none;
        }

        .login-button {
            display: inline-block;
            padding: 5px 17px;

            background-color: #eaeaea;
            border: none;
            border-radius: 10px;
            font-size: 16px;
            font-weight: bold;
            text-decoration: none;
            color: #333;
            transition: background-color 0.3s ease;
        }

        .login-button:hover {
            background-color: #d4d4d4;
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li>Timezone: <strong style="font-weight: bold;" id="user-timezone"></strong></li>
                    <li>Date: <strong style="font-weight: bold;" id="current-date"></strong></li>
                    <li>Current Time: <strong style="font-weight: bold;" id="current-time"></strong></li>
                    <li><a class="login-button" href="{% url 'index' %}">Home</a></li>

                    {% for group in user.groups.all %}
                        {% if group.name == 'Customer' %}
                            <li><a class="login-button" href="{% url 'servicepacks' %}">All service packs</a></li>
                            <li><a class="login-button" href="{% url 'cart:cart_detail' %}">Cart</a></li>
                        {% endif %}
                    {% endfor %}

                    {% for group in user.groups.all %}
                        {% if group.name == 'Staff' %}
                            <li><a class="login-button" href="{% url 'order:orders' %}">All orders</a></li>
                        {% endif %}
                    {% endfor %}

                    {% for group in user.groups.all %}
                        {% if group.name == 'Admin' %}
                            <li><a class="login-button" href="{% url 'servicepacks' %}">All service packs</a></li>
                            <li><a class="login-button" href="{% url 'order:orders' %}">All orders</a></li>
                            <li><a class="login-button" href="{% url 'administration:list_servicepack' %}">Edit
                                stuff</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if user.is_authenticated %}
                        <li>User: <strong style="font-weight: bold">{{ user.get_username }}</strong></li>
                        <li><a class="login-button" style="background-color:orangered"
                               href="{% url 'logout' %}?next={{ '' }}">Logout</a></li>
                    {% else %}
                        <li><a class="login-button" href="{% url 'servicepacks' %}">All service packs</a></li>
                        <li><a class="login-button" href="{% url 'register' %}?next={{ '' }}">Register</a></li>
                        <li><a class="login-button" href="{% url 'login' %}?next={{ '/cleaning' }}">Login</a></li>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}
        </div>
    </div>
</div>

<script>
    function updateTime() {
        var currentTime = new Date();
        var hours = currentTime.getHours();
        var minutes = currentTime.getMinutes();
        var seconds = currentTime.getSeconds();
        var month = currentTime.getMonth() + 1;
        var day = currentTime.getDate();
        var year = currentTime.getFullYear();

        // Add leading zeros to hours, minutes, and seconds if they are less than 10
        hours = (hours < 10 ? "0" : "") + hours;
        minutes = (minutes < 10 ? "0" : "") + minutes;
        seconds = (seconds < 10 ? "0" : "") + seconds;

        // Update the current time element in the HTML
        document.getElementById("current-time").textContent = hours + ":" + minutes + ":" + seconds;
        document.getElementById("current-date").textContent = day + "/" + month + "/" + year;

        // Schedule the next update in 1 second
        setTimeout(updateTime, 1000);
    }

    // Get the user's timezone using pytz library and update the HTML element
    fetch("https://worldtimeapi.org/api/ip")
        .then((response) => response.json())
        .then((data) => {
            var userTimezone = data.timezone;
            document.getElementById("user-timezone").textContent = userTimezone;
        })
        .catch((error) => console.log(error));

    // Call the updateTime function to start updating the current time and date
    updateTime();
</script>


</body>

</html>

Lab4/cleaning/templates/index.html
{% extends "base_generic.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
{% block content %}
    <h1>Cleaning company Home</h1>
    <p>
        Welcome to Cleaning company
    </p>
    <h2>Packs:</h2>

    <ul>
        <li><strong>Service Packs:</strong> {{ num_service_packs }}</li>
        <li><strong>All offered service packs</strong> {{ num_instances }}</li>
        <li><strong>Available service packs for particular dates:</strong> {{ num_instances_available }}</li>
    </ul>
    <h2>Kanye West Quote:</h2>
    <p>{{ quote }}</p>

    <h2>Age Lookup</h2>
    <form method="post" action="">
        {% csrf_token %}
        <label for="name">Enter Name:</label>
        <input type="text" name="name" id="name" required>
        <button type="submit">Get Age</button>
    </form>

    {% if age %}
        <h2>Age:</h2>
        <p>Name: {{ name }}</p>
        <p>Age: {{ age }}</p>
    {% endif %}
{% endblock %}